version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www/html
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=base64:YOUR_APP_KEY
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000

      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=your_db_name
      - DB_USERNAME=your_db_user
      - DB_PASSWORD=your_db_password

    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_DATABASE=your_db_name
      - MYSQL_USER=your_db_user
      - MYSQL_PASSWORD=your_db_password

volumes:
  db_data:
